ns-consulting/ns_consulting/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

admin.autodiscover()

urlpatterns = [
    url(r'^sitemap\.xml$', sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}}),
]

urlpatterns += i18n_patterns(
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = [
        url(r'^media/(?P<path>.*)$', serve,
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ] + staticfiles_urlpatterns() + urlpatterns

ns-consulting/polls/urls.py
from django.conf.urls import url

from . import views

app_name = "polls"
urlpatterns = [
    url(
        r'^$',
        views.IndexView.as_view(),
        name='index'
    ),
    url(
        r'^(?P<pk>\d+)/$',
        views.DetailView.as_view(),
        name='detail'
    ),
    url(
        r'^(?P<pk>\d+)/results/$',
        views.ResultsView.as_view(),
        name='results'
    ),
    url(
        r'^(?P<poll_id>\d+)/vote/(?P<choice_id>\d+)/$',
        views.vote,
        name='vote'
    ),
]

ns-consulting/posts/urls.py
from django.conf.urls import url

from . import views

app_name = "posts"
urlpatterns = [
    url(
        r'^search/$',
        views.PostSearchListView.as_view(),
        name='post_search_list_view',
    ),
]

ns-consulting/polls/models.py
from django.utils.translation import ugettext_lazy as _

from cms.models import CMSPlugin
from django.db import models


class Poll(models.Model):
    question = models.CharField(
        verbose_name=_('Вопрос'),
        max_length=255,
        blank=False,
        default=None,
    )

    class Meta:
        verbose_name = 'Опрос'
        verbose_name_plural = 'Опросы'

    def __str__(self):
        return self.question


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    percent = models.IntegerField(default=0, editable=False)

    class Meta:
        verbose_name = 'Выбор'
        verbose_name_plural = 'Выборы'

    def __str__(self):
        return self.choice_text


class PollPluginModel(CMSPlugin):
    poll = models.ForeignKey(Poll)

    def __unicode__(self):
        return self.poll.question

ns-consulting/posts/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from cms.models.fields import PageField
from djangocms_text_ckeditor.models import AbstractText


class PostPluginModel(AbstractText):
    link = PageField(
        verbose_name=_('Ссылка'),
        blank=False,
        null=False,
    )

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

    def __unicode__(self):
        if self.title:
            return self.title
        return 'новость %d' % self.id

ns-consulting/polls/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.views import generic

from .models import Choice, Poll

from .vote_helpers import update_percents


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        return Poll.objects.all()[:5]


class DetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'


def vote(request, poll_id, choice_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    selected_choice = poll.choice_set.get(pk=choice_id)

    selected_choice.votes += 1
    selected_choice.save()

    update_percents(poll)
    request.session['poll_has_been_voted'] = True
    return HttpResponseRedirect(reverse('polls:results', args=(poll.id,)))

ns-consulting/posts/views.py
import operator
from functools import reduce

from django.db.models import Q
from django.views.generic import ListView
from django.urls.exceptions import NoReverseMatch

from .models import PostPluginModel

from .search_helpers import get_duplicate_ids


class PostSearchListView(ListView):
    model = PostPluginModel
    template_name = 'posts/search_results.html'

    def get_queryset(self):
        search_results = super(PostSearchListView, self).get_queryset()

        query = self.request.GET.get('q')
        if not query:
            return None

        query_list = query.split()
        search_results = search_results.filter(
            reduce(
                operator.and_,
                (Q(body__icontains=q) for q in query_list)
            ) | reduce(
                operator.and_,
                (Q(body__icontains=q.capitalize()) for q in query_list)
            ) | reduce(
                operator.and_,
                (Q(body__icontains=q.upper()) for q in query_list)
            ) | reduce(
                operator.and_,
                (Q(body__icontains=q.lower()) for q in query_list)
            )
        ).exclude(id__in=get_duplicate_ids())

        return search_results

    def get_context_data(self, **kwargs):
        context = super(PostSearchListView, self).get_context_data(**kwargs)

        query = self.request.GET.get('q')
        if not query:
            context['search_query'] = ''
        else:
            context['search_query'] = query

        search_results = self.get_queryset()
        context['search_results'] = search_results

        return context

ns-consulting/custom_plugins/templates/file_background_img.html
{% load cms_tags %}{% spaceless %}

{% endspaceless %}<a class="text-under-img-wrapper" href="{{ instance.file_src.url }}"{% if instance.link_target %} target="{{ instance.link_target }}"{% endif %}{% if instance.attributes_str %} {{ instance.attributes_str }}{% endif %}>{% if instance.show_file_size %}<span>{{ instance.file_src.size|filesizeformat }}</span>{% endif %}{% for plugin in instance.child_plugin_instances %}{% render_plugin plugin %}{% empty %}{{ instance.name }}{% endfor %}</a>{% spaceless %}

{% endspaceless %}{% comment %}
    # https://github.com/divio/django-filer/blob/master/filer/models/filemodels.py
    {{ instance.file_src }}
    {{ instance.file_src.extension }}
    # Available variables:
    {{ instance.template }}
    {{ instance.file_name }}
    {{ instance.link_target }}
    {{ instance.link_title }}
    {{ instance.show_file_size }}
    {{ instance.attributes_str }}
{% endcomment %}

ns-consulting/custom_plugins/templates/file_link_background_img.html
{% load cms_tags %}{% spaceless %}

{% endspaceless %}<a class="text-under-img-wrapper" href="{{ instance.file_src.url }}"{% if instance.link_target %} target="{{ instance.link_target }}"{% endif %}{% if instance.attributes_str %} {{ instance.attributes_str }}{% endif %}>{% if instance.show_file_size %}<span>{{ instance.file_src.size|filesizeformat }}</span>{% endif %}{% for plugin in instance.child_plugin_instances %}{% render_plugin plugin %}{% empty %}{{ instance.name }}{% endfor %}</a>{% spaceless %}

{% endspaceless %}{% comment %}
    # https://github.com/divio/django-filer/blob/master/filer/models/filemodels.py
    {{ instance.file_src }}
    {{ instance.file_src.extension }}
    # Available variables:
    {{ instance.template }}
    {{ instance.file_name }}
    {{ instance.link_target }}
    {{ instance.link_title }}
    {{ instance.show_file_size }}
    {{ instance.attributes_str }}
{% endcomment %}

ns-consulting/custom_plugins/templates/link_background_img.html
{% load cms_tags %}{% spaceless %}

{% endspaceless %}<a class="text-under-img-wrapper" href="{{ link }}"{% if instance.target %} target="{{ instance.target }}"{% endif %}{% if instance.attributes %} {{ instance.attributes_str }}{% endif %}>{% for plugin in instance.child_plugin_instances %}{% render_plugin plugin %}{% empty %}{{ instance.name }}{% endfor %}</a>{% spaceless %}

{% endspaceless %}{% comment %}
    # https://github.com/divio/django-filer/blob/master/filer/models/filemodels.py
    {{ instance.file_src }}
    {{ instance.file_src.extension }}
    # Available variables:
    {{ instance.template }}
    {{ instance.file_name }}
    {{ instance.link_target }}
    {{ instance.link_title }}
    {{ instance.show_file_size }}
    {{ instance.attributes_str }}
{% endcomment %}

ns-consulting/ns_consulting/templates/base.html
{% load cms_tags menu_tags sekizai_tags %}
{% load static %}
<!doctype html>
<html>
  <head>
  <title>{% block title %}ns-consulting{% endblock title %}</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <style type="text/css">
  .nav {
    padding-left: 0;
  }
  .nav li {
    display: inline;
    list-style-type: none;
    padding-right: 20px;
  }
  .container {
    width: 940px;
    margin: 0 auto
  }
  .content {
    float: left;
    width: 80%;
  }
  .sidebar {
    float: left;
    width: 20%;
  }
  </style>
  <link rel="stylesheet" href="{% static "css/flexboxgrid2.css" %}">
  <link rel="stylesheet" href="{% static "css/main.css" %}">
  <link rel="stylesheet" href="{% static "css/banners_hower.css" %}">
  <link rel="stylesheet" href="{% static "css/media_queries.css" %}">
  <link href="{% static "css/hamburgers.css" %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static "css/search_popup.css" %}">
  {% render_block "css" %}
</head>
<body>
  {% cms_toolbar %}
  <header>
    <div class="hidden-sm headerLG">
      <img src="{% static "img/logo-LG.png" %}" alt="Logo">
    </div>
    <nav class="center-xs navbar" id="topNavbar">
      <div style="width: 25%;">
        <button class="hamburger hamburger--spin" type="button">
          <span class="hamburger-box">
            <span class="hamburger-inner"></span>
          </span>
        </button>
      </div>
      <div class="logoSmall-wrapper" style="width: 50%;">
        <a href="" class="logoSmall">
          <img class="logo-sm-img" src=" {% static "img/logo-SM.png" %}" alt="logo">
          <img class="logo-xs-img" src="{% static "img/logo-XS.png" %}" alt="logo">
        </a>
      </div>
      <div class="search-button-MD" style="width: 25%;">
        <button type="submit" class="searcher-submit-btn" onclick="openSearchMobile()">
          <img src="{% static "img/loupe.png" %}" alt="">
        </button>
      </div>
      <span class="navbar-LG-item"><a href="">Главная</a></span>
      <span class="navbar-LG-item"><a href="">О союзе</a></span>
      <span class="navbar-LG-item"><a href="">Услуги</a></span>
      <span class="navbar-LG-item"><a href="">Топ-5 событий</a></span>
      <span class="navbar-LG-item"><a href="">Семинары</a></span>
      <span class="navbar-LG-item"><a href="">Контакты</a></span>
      <span class="navbar-LG-item"><a href="">Партнеры</a></span>
    </nav>
    <nav class="row hidden-md start-xs navbar" id="topNavbarSM">
      <div class="col-xs-12">
        <a href="">Главная</a>
      </div>
      <div class="col-xs-12">
        <a href="">О союзе</a>
      </div>
      <div class="col-xs-12">
        <a href="">Услуги</a>
      </div>
      <div class="col-xs-12">
        <a href="">Топ-5 событий</a>
      </div>
      <div class="col-xs-12">
        <a href="">Семинары</a>
      </div>
      <div class="col-xs-12">
        <a href="">Контакты</a>
      </div>
      <div class="col-xs-12">
        <a href="">Партнеры</a>
      </div>
    </nav>
  </header>
  <div class="banner-right-1-XS-wrapper">
    <div class="col-xs-12 hidden-md hidden-lg hidden-xl banners-right banner-right-1 banner-right-1-XS">
        {% block right_1_XS %}{% endblock right_1_XS %}
        <a href="" id="arrowRight" class="arrow-right">
          <img src="{% static "img/arrow-right.png" %}" alt="arrow-right">
        </a>
    </div>
  </div>
  <div class="hidden-lg hidden-xl headerMD">
    <img src="{% static "img/logo-MD.png" %}" alt="Logo">
  </div>
  <div class="container main">
    <div class="row searcher-wrapper">
      <div class="col-md-11 searcher-input-wrapper">
        <form id="searchForm" action="{% url 'posts:post_search_list_view' %}" method="get" accept-charset="utf-8">
          <input class="searcher-input" id="searchBox" name="q" type="text" placeholder="Поиск..." >
        </form>
      </div>
      <div class="searcher-btn-wrapper">
        <button id="searchButton" class="searcher-submit-btn" type="submit">
          <img src="{% static "img/loupe.png" %}" alt="">
        </button>
      </div>
    </div>
    <div class="row banners banners-center-xs-sm">
      <div class="col-xs-12 start-xs banners-center">
        <div class="col-xs-12">
          {% block center_1_SM %}{% endblock center_1_SM %}
        </div>
        <div class="col-xs-12 banner-center-2">
          {% block center_2_SM %}{% endblock center_2_SM %}
        </div>
        <div class="col-xs-12">
          {% block center_3_SM %}{% endblock center_3_SM %}
        </div>
        <div class="col-xs-12">
          {% block center_4_SM %}{% endblock center_4_SM %}
        </div>
      </div>
    </div>
    <div class="row banners">
      <div class="col-xs-6 col-lg-3 hidden-md center-xs banners-left">
        <div class="col-xs-12 col-md-12 col-lg-12 banner-left-1">
          {% block left_1 %}{% endblock left_1 %}
        </div>
        <div class="col-xs-12 col-md-12 col-lg-12">
          {% block left_2 %}{% endblock left_2 %}
        </div>
        <div class="col-xs-12 col-md-12 col-lg-12 banner-left-3">
          {% block left_3 %}{% endblock left_3 %}
        </div>
        <div class="col-xs-12 col-md-12 col-lg-12 banner-left-4">
          {% block left_4 %}{% endblock left_4 %}
        </div>
        <div class="col-xs-12 col-md-12 col-lg-12 hidden-xs hidden-sm">
          {% block left_5 %}{% endblock left_5 %}
        </div>
      </div>
      <div class="col-md-8 col-lg-6 start-xs banners-center banners-center-md-lg">
        <div class="col-xs-12">
          {% block center_1 %}{% endblock center_1 %}
        </div>
        <div class="col-xs-12 banner-center-2">
          {% block center_2 %}{% endblock center_2 %}
        </div>
        <div class="col-xs-12">
          {% block center_3 %}{% endblock center_3 %}
        </div>
        <div class="col-xs-12 hidden-lg hidden-xl banner-center-5">
          {% block center_5 %}{% endblock center_5 %}
        </div>
        <div class="col-xs-12 hidden-lg hidden-xl">
          {% block center_6 %}{% endblock center_6 %}
        </div>
      </div>
      <div class="col-xs-6 col-md-4 col-lg-3 last-xs center-xs banners-right">
        <div class="col-xs-12 col-lg-12 hidden-xs hidden-sm first-md banner-right-1">
          {% block right_1 %}{% endblock right_1 %}
        </div>
        <div class="col-xs-12 col-lg-12 hidden-md">
          {% block right_2 %}{% endblock right_2 %}
        </div>
        <div class="col-lg-12 hidden-xs hidden-sm hidden-md">
          {% block right_3 %}{% endblock right_3 %}
        </div>
        <div class="col-xs-12 col-lg-12 hidden-md banner-right-4-MD">
          {% block right_4 %}{% endblock right_4 %}
        </div>
        <div class="col-xs-12 col-md-12 col-lg-12 first-md last-lg banner-right-5">
          {% block right_5 %}{% endblock right_5 %}
        </div>
        <div class="col-md-12 hidden-xs hidden-sm hidden-lg hidden-xl">
          {% block left_1_MD %}{% endblock left_1_MD %}
        </div>
        <div class="col-md-12 hidden-xs hidden-sm hidden-lg hidden-xl">
          {% block left_2_MD %}{% endblock left_2_MD %}
        </div>
        <div class="col-md-12 hidden-xs hidden-sm hidden-lg hidden-xl banner-left-3">
          {% block left_3_MD %}{% endblock left_3_MD %}
        </div>
        <div class="col-md-12 hidden-xs hidden-sm hidden-lg hidden-xl banner-left-4">
          {% block left_4_MD %}{% endblock left_4_MD %}
        </div>
        <div class="col-md-12 hidden-lg hidden-xl">
          {% block right_2_MD %}{% endblock right_2_MD %}
        </div>
        <div class="col-md-12 hidden-xs hidden-sm hidden-lg hidden-xl">
          {% block right_4_MD %}{% endblock right_4_MD %}
        </div>
        <div class="col-xs-12 hidden-lg hidden-xl">
          {% block left_5_XS_MD %}{% endblock left_5_XS_MD %}
        </div>
      </div>
    </div>
  </div>
  <nav class="center-xs navbar" id="bottomNavbar">
    <div class="col-xs-12">
      <span><a href="">Главная</a></span>
      <span><a href="">О союзе</a></span>
      <span><a href="">Услуги</a></span>
      <span><a href="">Топ-5 событий</a></span>
      <span><a href="">Семинары</a></span>
      <span><a href="">Контакты</a></span>
      <span><a href="">Партнеры</a></span>
    </div>
  </nav>
  <footer class="container">
    <div class="end-lg end-md right-col-md">
      <a href=""><img src="{% static "img/mailru-rating.png" %}" alt="img1"></a>
      <a href=""><img src="{% static "img/rating.png" %}" alt="img2"></a>
      <a href=""><img src="{% static "img/rambler-rating.png" %}" alt="img3"></a>
    </div>
    <div class="left-col">
      <p class="copyright">Lorem ipsum dolor sit amet,<br> consectetur adipisicing elit. Minus at, accusantium architecto omnis dolores,<br> pariatur voluptatibus rem itaque odio.</p>
    </div>
    <div class="end-lg end-md right-col-sm">
      <a href=""><img src="{% static "img/mailru-rating.png" %}" alt="img1"></a>
      <a href=""><img src="{% static "img/rating.png" %}" alt="img2"></a>
      <a href=""><img src="{% static "img/rambler-rating.png" %}" alt="img3"></a>
    </div>
  </footer>
  <div id="searchMobile" class="overlay">
    <div class="row overlay-content">
      <a href="javascript:void(0)" class="col-xs-12 closebtn" onclick="closeSearchMobile()">&times;</a>
    </div>
    <div class="row center-xs overlay-content">
      <form class="col-xs-12 popup-form" action="{% url 'posts:post_search_list_view' %}" method="get" accept-charset="utf-8">
        <input class="" id="searchBox" name="q" type="text" placeholder="Поиск..." >
        <button class="popup-button" type="submit">
          <img src="{% static "img/loupe.png" %}" alt="">
        </button>
      </form>
    </div>
  </div>
  <script src='{% static "js/navbarBurger.js" %}'></script>
  <script src='{% static "js/searchButton.js" %}'></script>
  <script src='{% static "js/arrowRight.js" %}'></script>
  {% render_block "js" %}
</body>
</html>

ns-consulting/ns_consulting/templates/djangocms_file/default/file.html
{% load cms_tags %}{% spaceless %}

{% endspaceless %}<a href="{{ instance.file_src.url }}"{% if instance.link_target %} target="{{ instance.link_target }}"{% endif %}{% if instance.attributes_str %} {{ instance.attributes_str }}{% endif %}>{% if instance.show_file_size %}<span>{{ instance.file_src.size|filesizeformat }}</span>{% endif %}{% for plugin in instance.child_plugin_instances %}{% render_plugin plugin %}{% empty %}{{ instance.name }}{% endfor %}</a>{% spaceless %}

{% endspaceless %}{% comment %}
    # https://github.com/divio/django-filer/blob/master/filer/models/filemodels.py
    {{ instance.file_src }}
    {{ instance.file_src.extension }}
    # Available variables:
    {{ instance.template }}
    {{ instance.file_name }}
    {{ instance.link_target }}
    {{ instance.link_title }}
    {{ instance.show_file_size }}
    {{ instance.attributes_str }}
{% endcomment %}

ns-consulting/ns_consulting/templates/fullwidth.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block left_1 %}
  {% static_placeholder "left 1" %}
{% endblock left_1 %}

{% block left_1_MD %}
  {% static_placeholder "left 1" %}
{% endblock left_1_MD %}

{% block left_2 %}
  {% static_placeholder "left 2" %}
{% endblock left_2 %}

{% block left_2_MD %}
  {% static_placeholder "left 2" %}
{% endblock left_2_MD %}

{% block left_3 %}
  {% static_placeholder 'left 3' %}
{% endblock left_3 %}

{% block left_3_MD %}
  {% static_placeholder 'left 3' %}
{% endblock left_3_MD %}

{% block left_4 %}
  {% static_placeholder "left 4" %}
{% endblock left_4 %}

{% block left_4_MD %}
  {% static_placeholder 'left 4' %}
{% endblock left_4_MD %}

{% block left_5 %}
  {% static_placeholder "left 5" %}
{% endblock left_5 %}

{% block left_5_XS_MD %}
  {% static_placeholder "left 5" %}
{% endblock left_5_XS_MD %}

{% block center_1 %}
  {% placeholder "center 1" %}
{% endblock center_1 %}

{% block center_2 %}
  {% placeholder "center 2" %}
{% endblock center_2 %}

{% block center_3 %}
  {% placeholder "center 3" %}
{% endblock center_3 %}

{% block center_4 %}
  {% placeholder "center 4" %}
{% endblock center_4 %}

{% block center_5 %}
  {% placeholder "center 5" %}
{% endblock center_5 %}

{% block center_6 %}
  {% placeholder "center 6" %}
{% endblock center_6 %}

{% block right_1 %}
  {% static_placeholder "right 1" %}
{% endblock right_1 %}

{% block right_1_XS %}
  {% static_placeholder "right 1" %}
{% endblock right_1_XS %}

{% block right_2 %}
  {% static_placeholder "right 2" %}
{% endblock right_2 %}

{% block right_2_MD %}
  {% static_placeholder "right 2" %}
{% endblock right_2_MD %}

{% block right_3 %}
  {% static_placeholder 'right 3' %}
{% endblock right_3 %}

{% block right_4 %}
  {% static_placeholder 'right 4' %}
{% endblock right_4 %}

{% block right_4_MD %}
  {% static_placeholder 'right 4' %}
{% endblock right_4_MD %}

{% block right_5 %}
  {% static_placeholder 'right 5' %}
{% endblock right_5 %}

ns-consulting/ns_consulting/templates/left_and_right_save.html
{% extends "base.html" %}
{% load cms_tags %}

{% block title %}{% page_attribute "page_title" %}{% endblock title %}

{% block left_1 %}
  {% static_placeholder "left 1" %}
{% endblock left_1 %}

{% block left_1_MD %}
  {% static_placeholder "left 1" %}
{% endblock left_1_MD %}

{% block left_2 %}
  {% static_placeholder "left 2" %}
{% endblock left_2 %}

{% block left_2_MD %}
  {% static_placeholder "left 2" %}
{% endblock left_2_MD %}

{% block left_3 %}
  {% static_placeholder 'left 3' %}
{% endblock left_3 %}

{% block left_3_MD %}
  {% static_placeholder 'left 3' %}
{% endblock left_3_MD %}

{% block left_4 %}
  {% static_placeholder "left 4" %}
{% endblock left_4 %}

{% block left_4_MD %}
  {% static_placeholder 'left 4' %}
{% endblock left_4_MD %}

{% block left_5 %}
  {% static_placeholder "left 5" %}
{% endblock left_5 %}

{% block left_5_XS_MD %}
  {% static_placeholder "left 5" %}
{% endblock left_5_XS_MD %}

{% block center_1 %}
  {% placeholder "center 1" %}
{% endblock center_1 %}

{% block center_2 %}
  {% placeholder "center 2" %}
{% endblock center_2 %}

{% block center_3 %}
  {% placeholder "center 3" %}
{% endblock center_3 %}

{% block center_4 %}
  {% placeholder "center 4" %}
{% endblock center_4 %}

{% block center_5 %}
  {% placeholder "center 5" %}
{% endblock center_5 %}

{% block center_6 %}
  {% placeholder "center 6" %}
{% endblock center_6 %}

{% block right_1 %}
  {% static_placeholder "right 1" %}
{% endblock right_1 %}

{% block right_1_XS %}
  {% static_placeholder "right 1" %}
{% endblock right_1_XS %}

{% block right_2 %}
  {% static_placeholder "right 2" %}
{% endblock right_2 %}

{% block right_2_MD %}
  {% static_placeholder "right 2" %}
{% endblock right_2_MD %}

{% block right_3 %}
  {% static_placeholder 'right 3' %}
{% endblock right_3 %}

{% block right_4 %}
  {% static_placeholder 'right 4' %}
{% endblock right_4 %}

{% block right_4_MD %}
  {% static_placeholder 'right 4' %}
{% endblock right_4_MD %}

{% block right_5 %}
  {% static_placeholder 'right 5' %}
{% endblock right_5 %}

ns-consulting/polls/templates/polls/detail.html
<div class="poll">
  <div class="banner-content">
    <p class="poll-header">Опрос</p>
    <p class="poll-question">{{ instance.poll.question }}</p>
  </div>
  {% for choice in instance.poll.choice_set.all %}
    <a href="{% url 'polls:vote' instance.poll.id choice.id %}">
      {{ choice.choice_text }}
    </a>
  {% endfor %}
</div>

ns-consulting/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block polls_content %}
<h1>Polls</h1>
{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
		<li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

ns-consulting/polls/templates/polls/results.html
{% extends "main_page.html" %}
{% load static %}

{% block right_5 %}
  <link rel="stylesheet" href="{% static "polls/poll.css" %}">
  <link rel="stylesheet" href="{% static "polls/results.css" %}">
  <div class="poll">
    <div class="banner-content">
      <p class="poll-header">Опрос</p>
      <p class="poll-question">{{ poll.question }}</p>
    </div>
    {% for choice in poll.choice_set.all %}
      <div class="col-xs-12">
        {{ choice.choice_text }}
        <div class="filled-poll-choice">
          <div class="col-xs-12 start-xs" style="width: {{ choice.percent }}%;">{{ choice.percent }}%</div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock right_5 %}

ns-consulting/polls/templates/polls_cms_integration/poll_plugin.html
{% load static %}
<link rel="stylesheet" href="{% static "polls/poll.css" %}">

<div class="poll">
  <div class="banner-content">
    <p class="poll-header">Опрос</p>
    <p class="poll-question">{{ instance.poll.question }}</p>
  </div>
  {% for choice in instance.poll.choice_set.all %}
    <div class="col-xs-12">
      <a href="{% url 'polls:vote' instance.poll.id choice.id %}" class="poll-choice">
        {{ choice.choice_text }}
      </a>
    </div>
  {% endfor %}
</div>

ns-consulting/posts/templates/posts/post_plugin.html
<h1 style="font-size: 1.5rem;">{{ instance.title }}</h1>
{{ instance.body|safe }}